2020-05-22 15:27:26,872 ERROR Axure.DataBase.Module_Sale.OrderSaleDAO - Error al Mostrar orden de venta por numero de orden. Referencia a objeto no establecida como instancia de un objeto.   en Axure.DataBase.Module_Sale.OrderSaleDAO.GetByNumber(String number) en C:\Users\Usuario\Desktop\Modulo_Ventas\Axure\back_end\Axure\DataBase\Module_Sale\OrderSaleDAO.cs:línea 160
2020-05-25 17:16:32,830 ERROR Axure.DataBase.Module_Sale.OrderSaleDAO - Error al mostrar el listado de orden de venta por Id. Error relacionado con la red o específico de la instancia mientras se establecía una conexión con el servidor SQL Server. No se encontró el servidor o éste no estaba accesible. Compruebe que el nombre de la instancia es correcto y que SQL Server está configurado para admitir conexiones remotas. (provider: SQL Network Interfaces, error: 50 - Se produjo un error de Local Database Runtime. Error durante el inicio de la instancia de LocalDB: no se pudo iniciar el proceso de SQL Server.
)   en System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)
   en System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   en System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   en System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   en System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   en System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   en System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   en System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   en System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   en System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   en System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   en System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   en System.Data.SqlClient.SqlConnection.Open()
   en System.Data.Entity.Infrastructure.Interception.DbConnectionDispatcher.<Open>b__36(DbConnection t, DbConnectionInterceptionContext c)
   en System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext](TTarget target, Action`2 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   en System.Data.Entity.Infrastructure.Interception.DbConnectionDispatcher.Open(DbConnection connection, DbInterceptionContext interceptionContext)
   en System.Data.Entity.SqlServer.SqlProviderServices.<>c__DisplayClass33.<UsingConnection>b__32()
   en System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.<>c__DisplayClass1.<Execute>b__0()
   en System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   en System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute(Action operation)
   en System.Data.Entity.SqlServer.SqlProviderServices.UsingConnection(DbConnection sqlConnection, Action`1 act)
   en System.Data.Entity.SqlServer.SqlProviderServices.UsingMasterConnection(DbConnection sqlConnection, Action`1 act)
   en System.Data.Entity.SqlServer.SqlProviderServices.CreateDatabaseFromScript(Nullable`1 commandTimeout, DbConnection sqlConnection, String createDatabaseScript)
   en System.Data.Entity.SqlServer.SqlProviderServices.DbCreateDatabase(DbConnection connection, Nullable`1 commandTimeout, StoreItemCollection storeItemCollection)
   en System.Data.Entity.Core.Common.DbProviderServices.CreateDatabase(DbConnection connection, Nullable`1 commandTimeout, StoreItemCollection storeItemCollection)
   en System.Data.Entity.Core.Objects.ObjectContext.CreateDatabase()
   en System.Data.Entity.Migrations.Utilities.DatabaseCreator.Create(DbConnection connection)
   en System.Data.Entity.Migrations.DbMigrator.EnsureDatabaseExists(Action mustSucceedToKeepDatabase)
   en System.Data.Entity.Migrations.DbMigrator.Update(String targetMigration)
   en System.Data.Entity.Internal.DatabaseCreator.CreateDatabase(InternalContext internalContext, Func`3 createMigrator, ObjectContext objectContext)
   en System.Data.Entity.Internal.InternalContext.CreateDatabase(ObjectContext objectContext, DatabaseExistenceState existenceState)
   en System.Data.Entity.Database.Create(DatabaseExistenceState existenceState)
   en System.Data.Entity.CreateDatabaseIfNotExists`1.InitializeDatabase(TContext context)
   en System.Data.Entity.Internal.InternalContext.<>c__DisplayClassf`1.<CreateInitializationAction>b__e()
   en System.Data.Entity.Internal.InternalContext.PerformInitializationAction(Action action)
   en System.Data.Entity.Internal.InternalContext.PerformDatabaseInitialization()
   en System.Data.Entity.Internal.LazyInternalContext.<InitializeDatabase>b__4(InternalContext c)
   en System.Data.Entity.Internal.RetryAction`1.PerformAction(TInput input)
   en System.Data.Entity.Internal.LazyInternalContext.InitializeDatabaseAction(Action`1 action)
   en System.Data.Entity.Internal.LazyInternalContext.InitializeDatabase()
   en System.Data.Entity.Internal.InternalContext.GetEntitySetAndBaseTypeForType(Type entityType)
   en System.Data.Entity.Internal.Linq.InternalSet`1.Initialize()
   en System.Data.Entity.Internal.Linq.InternalSet`1.get_InternalContext()
   en System.Data.Entity.Internal.Linq.InternalSet`1.Find(Object[] keyValues)
   en System.Data.Entity.DbSet`1.Find(Object[] keyValues)
   en Axure.DataBase.Module_Sale.OrderSaleDAO.GetById(Int32 Id) en C:\Users\Usuario\Desktop\Modulo_Ventas\Axure\back_end\Axure\DataBase\Module_Sale\OrderSaleDAO.cs:línea 169
2020-05-25 17:23:33,321 ERROR Axure.DataBase.Module_Sale.OrderSaleDetailDAO - Error al agregar detalle de la orden con Id 5 OrderSaleDetailDAOAn error occurred while updating the entries. See the inner exception for details.   en System.Data.Entity.Internal.InternalContext.SaveChanges()
   en System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   en System.Data.Entity.DbContext.SaveChanges()
   en Axure.DataBase.Module_Sale.OrderSaleDetailDAO.Add(OrderSaleDetailDTO sod, AxureContext db) en C:\Users\Usuario\Desktop\Modulo_Ventas\Axure\back_end\Axure\DataBase\Module_Sale\OrderSaleDetailDAO.cs:línea 24
2020-05-25 17:23:33,402 ERROR Axure.DataBase.Module_Sale.OrderSaleDetailDAO - Error al agregar detalle de la orden con Id 5 OrderSaleDetailDAOThe operation cannot be completed because the DbContext has been disposed.   en System.Data.Entity.Internal.LazyInternalContext.InitializeContext()
   en System.Data.Entity.Internal.LazyInternalContext.get_ObjectContext()
   en System.Data.Entity.Internal.InternalContext.DetectChanges(Boolean force)
   en System.Data.Entity.Internal.Linq.InternalSet`1.ActOnSet(Action action, EntityState newState, Object entity, String methodName)
   en System.Data.Entity.Internal.Linq.InternalSet`1.Add(Object entity)
   en System.Data.Entity.DbSet`1.Add(TEntity entity)
   en Axure.DataBase.Module_Sale.OrderSaleDetailDAO.Add(OrderSaleDetailDTO sod, AxureContext db) en C:\Users\Usuario\Desktop\Modulo_Ventas\Axure\back_end\Axure\DataBase\Module_Sale\OrderSaleDetailDAO.cs:línea 23
2020-05-25 17:28:40,186 ERROR Axure.DataBase.Module_Sale.OrderSaleDetailDAO - Error al agregar detalle de la orden con Id 6 OrderSaleDetailDAOAn error occurred while updating the entries. See the inner exception for details.   en System.Data.Entity.Internal.InternalContext.SaveChanges()
   en System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   en System.Data.Entity.DbContext.SaveChanges()
   en Axure.DataBase.Module_Sale.OrderSaleDetailDAO.Add(OrderSaleDetailDTO sod) en C:\Users\Usuario\Desktop\Modulo_Ventas\Axure\back_end\Axure\DataBase\Module_Sale\OrderSaleDetailDAO.cs:línea 24
2020-05-25 17:28:40,267 ERROR Axure.DataBase.Module_Sale.OrderSaleDetailDAO - Error al agregar detalle de la orden con Id 6 OrderSaleDetailDAOAn error occurred while updating the entries. See the inner exception for details.   en System.Data.Entity.Internal.InternalContext.SaveChanges()
   en System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   en System.Data.Entity.DbContext.SaveChanges()
   en Axure.DataBase.Module_Sale.OrderSaleDetailDAO.Add(OrderSaleDetailDTO sod) en C:\Users\Usuario\Desktop\Modulo_Ventas\Axure\back_end\Axure\DataBase\Module_Sale\OrderSaleDetailDAO.cs:línea 24
2020-05-25 17:31:31,919 ERROR Axure.DataBase.Module_Sale.OrderSaleDetailDAO - Error al agregar detalle de la orden con Id 0 OrderSaleDetailDAOAn error occurred while updating the entries. See the inner exception for details.   en System.Data.Entity.Internal.InternalContext.SaveChanges()
   en System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   en System.Data.Entity.DbContext.SaveChanges()
   en Axure.DataBase.Module_Sale.OrderSaleDetailDAO.Add(OrderSaleDetailDTO sod, AxureContext db) en C:\Users\Usuario\Desktop\Modulo_Ventas\Axure\back_end\Axure\DataBase\Module_Sale\OrderSaleDetailDAO.cs:línea 24
2020-05-25 17:31:32,002 ERROR Axure.DataBase.Module_Sale.OrderSaleDetailDAO - Error al agregar detalle de la orden con Id 0 OrderSaleDetailDAOThe operation cannot be completed because the DbContext has been disposed.   en System.Data.Entity.Internal.LazyInternalContext.InitializeContext()
   en System.Data.Entity.Internal.LazyInternalContext.get_ObjectContext()
   en System.Data.Entity.Internal.InternalContext.DetectChanges(Boolean force)
   en System.Data.Entity.Internal.Linq.InternalSet`1.ActOnSet(Action action, EntityState newState, Object entity, String methodName)
   en System.Data.Entity.Internal.Linq.InternalSet`1.Add(Object entity)
   en System.Data.Entity.DbSet`1.Add(TEntity entity)
   en Axure.DataBase.Module_Sale.OrderSaleDetailDAO.Add(OrderSaleDetailDTO sod, AxureContext db) en C:\Users\Usuario\Desktop\Modulo_Ventas\Axure\back_end\Axure\DataBase\Module_Sale\OrderSaleDetailDAO.cs:línea 23
2020-05-25 17:31:32,062 ERROR Axure.DataBase.Module_Sale.OrderSaleDAO - Error al agregar orden de venta 100-001-004 Add OrderSaleDAO
2020-05-25 17:37:34,357 ERROR Axure.DataBase.Module_Sale.OrderSaleDetailDAO - Error al agregar detalle de la orden con Id 7 OrderSaleDetailDAOAn error occurred while updating the entries. See the inner exception for details.   en System.Data.Entity.Internal.InternalContext.SaveChanges()
   en System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   en System.Data.Entity.DbContext.SaveChanges()
   en Axure.DataBase.Module_Sale.OrderSaleDetailDAO.Add(OrderSaleDetailDTO sod, AxureContext db) en C:\Users\Usuario\Desktop\Modulo_Ventas\Axure\back_end\Axure\DataBase\Module_Sale\OrderSaleDetailDAO.cs:línea 24
2020-05-25 17:37:34,445 ERROR Axure.DataBase.Module_Sale.OrderSaleDetailDAO - Error al agregar detalle de la orden con Id 7 OrderSaleDetailDAOThe operation cannot be completed because the DbContext has been disposed.   en System.Data.Entity.Internal.LazyInternalContext.InitializeContext()
   en System.Data.Entity.Internal.LazyInternalContext.get_ObjectContext()
   en System.Data.Entity.Internal.InternalContext.DetectChanges(Boolean force)
   en System.Data.Entity.Internal.Linq.InternalSet`1.ActOnSet(Action action, EntityState newState, Object entity, String methodName)
   en System.Data.Entity.Internal.Linq.InternalSet`1.Add(Object entity)
   en System.Data.Entity.DbSet`1.Add(TEntity entity)
   en Axure.DataBase.Module_Sale.OrderSaleDetailDAO.Add(OrderSaleDetailDTO sod, AxureContext db) en C:\Users\Usuario\Desktop\Modulo_Ventas\Axure\back_end\Axure\DataBase\Module_Sale\OrderSaleDetailDAO.cs:línea 23
2020-05-25 17:38:02,609 ERROR Axure.DataBase.Module_Sale.OrderSaleDAO - Error al mostrar el listado de orden de venta por Id. Referencia a objeto no establecida como instancia de un objeto.   en Axure.DataBase.Module_Sale.OrderSaleDAO.GetById(Int32 Id) en C:\Users\Usuario\Desktop\Modulo_Ventas\Axure\back_end\Axure\DataBase\Module_Sale\OrderSaleDAO.cs:línea 142
2020-05-25 17:43:08,178 ERROR Axure.DataBase.Module_Sale.OrderSaleDetailDAO - Error al agregar detalle de la orden con Id 8 OrderSaleDetailDAOAn error occurred while updating the entries. See the inner exception for details.   en System.Data.Entity.Internal.InternalContext.SaveChanges()
   en System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   en System.Data.Entity.DbContext.SaveChanges()
   en Axure.DataBase.Module_Sale.OrderSaleDetailDAO.Add(OrderSaleDetailDTO sod) en C:\Users\Usuario\Desktop\Modulo_Ventas\Axure\back_end\Axure\DataBase\Module_Sale\OrderSaleDetailDAO.cs:línea 24
2020-05-25 17:43:08,253 ERROR Axure.DataBase.Module_Sale.OrderSaleDetailDAO - Error al agregar detalle de la orden con Id 8 OrderSaleDetailDAOAn error occurred while updating the entries. See the inner exception for details.   en System.Data.Entity.Internal.InternalContext.SaveChanges()
   en System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   en System.Data.Entity.DbContext.SaveChanges()
   en Axure.DataBase.Module_Sale.OrderSaleDetailDAO.Add(OrderSaleDetailDTO sod) en C:\Users\Usuario\Desktop\Modulo_Ventas\Axure\back_end\Axure\DataBase\Module_Sale\OrderSaleDetailDAO.cs:línea 24
2020-05-25 17:47:02,526 ERROR Axure.DataBase.Module_Sale.OrderSaleDetailDAO - Error al agregar detalle de la orden con Id 0 OrderSaleDetailDAOAn error occurred while updating the entries. See the inner exception for details.   en System.Data.Entity.Internal.InternalContext.SaveChanges()
   en System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   en System.Data.Entity.DbContext.SaveChanges()
   en Axure.DataBase.Module_Sale.OrderSaleDetailDAO.Add(OrderSaleDetailDTO sod) en C:\Users\Usuario\Desktop\Modulo_Ventas\Axure\back_end\Axure\DataBase\Module_Sale\OrderSaleDetailDAO.cs:línea 24
2020-05-25 17:49:42,849 ERROR Axure.DataBase.Module_Sale.OrderSaleDetailDAO - Error al agregar detalle de la orden con Id 0 OrderSaleDetailDAOAn error occurred while updating the entries. See the inner exception for details.   en System.Data.Entity.Internal.InternalContext.SaveChanges()
   en System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   en System.Data.Entity.DbContext.SaveChanges()
   en Axure.DataBase.Module_Sale.OrderSaleDetailDAO.Add(OrderSaleDetailDTO sod) en C:\Users\Usuario\Desktop\Modulo_Ventas\Axure\back_end\Axure\DataBase\Module_Sale\OrderSaleDetailDAO.cs:línea 24
2020-05-25 17:52:14,748 ERROR Axure.DataBase.Module_Sale.OrderSaleDetailDAO - Error al agregar detalle de la orden con Id 10 OrderSaleDetailDAOThe operation cannot be completed because the DbContext has been disposed.   en System.Data.Entity.Internal.LazyInternalContext.InitializeContext()
   en System.Data.Entity.Internal.LazyInternalContext.get_ObjectContext()
   en System.Data.Entity.Internal.InternalContext.DetectChanges(Boolean force)
   en System.Data.Entity.Internal.Linq.InternalSet`1.ActOnSet(Action action, EntityState newState, Object entity, String methodName)
   en System.Data.Entity.Internal.Linq.InternalSet`1.Add(Object entity)
   en System.Data.Entity.DbSet`1.Add(TEntity entity)
   en Axure.DataBase.Module_Sale.OrderSaleDetailDAO.Add(OrderSaleDetailDTO sod, AxureContext db) en C:\Users\Usuario\Desktop\Modulo_Ventas\Axure\back_end\Axure\DataBase\Module_Sale\OrderSaleDetailDAO.cs:línea 23
2020-05-27 15:48:07,037 ERROR Axure.DataBase.Module_Sale.OrderSaleDAO - Error al agregar orden de venta 100-00-09999 Add OrderSaleDAO
2020-05-27 15:51:34,121 ERROR Axure.DataBase.Module_Sale.OrderSaleDAO - Error al agregar orden de venta 100-00-09999 Add OrderSaleDAO
2020-05-28 23:15:06,927 ERROR Axure.DataBase.Module_Sale.InvoiceDAO - Error al agregar una factura!!!
2020-05-28 23:19:08,596 ERROR Axure.DataBase.Module_Sale.InvoiceDAO - Error al agregar una factura!!!
2020-05-31 21:46:49,733 ERROR Axure.DataBase.Module_Sale.InvoiceDAO - Error al agregar una factura!!!
2020-05-31 21:48:17,906 ERROR Axure.DataBase.Module_Sale.InvoiceDAO - Error al agregar una factura!!!
2020-05-31 21:48:41,824 ERROR Axure.DataBase.Module_Sale.InvoiceDAO - Error al agregar una factura!!!
2020-05-31 21:49:09,009 ERROR Axure.DataBase.Module_Sale.InvoiceDAO - Error al agregar una factura!!!
2020-05-31 21:52:28,661 ERROR Axure.DataBase.Module_Sale.InvoiceDAO - Error al agregar una factura!!!
2020-05-31 21:53:01,367 ERROR Axure.DataBase.Module_Sale.InvoiceDAO - Error al agregar una factura!!!
2020-05-31 21:53:18,396 ERROR Axure.DataBase.Module_Sale.InvoiceDAO - Error al agregar una factura!!!
2020-05-31 21:59:52,907 ERROR Axure.DataBase.Module_Sale.InvoiceDAO - Error al agregar una factura!!!
2020-05-31 22:21:17,571 ERROR Axure.DataBase.Module_Sale.InvoiceDAO - Error al agregar una factura!!!
2020-05-31 22:21:23,940 ERROR Axure.DataBase.Module_Sale.InvoiceDAO - Error al agregar una factura!!!
2020-05-31 22:21:54,812 ERROR Axure.DataBase.Module_Sale.InvoiceDAO - Error al agregar una factura!!!
2020-05-31 22:21:58,794 ERROR Axure.DataBase.Module_Sale.InvoiceDAO - Error al agregar una factura!!!
2020-05-31 22:22:34,853 ERROR Axure.DataBase.Module_Sale.InvoiceDAO - Error al agregar una factura!!!
2020-05-31 22:24:35,558 ERROR Axure.DataBase.Module_Sale.InvoiceDAO - Error al agregar una factura!!!
2020-05-31 22:26:07,024 ERROR Axure.DataBase.Module_Sale.InvoiceDAO - Error al agregar una factura!!!
2020-06-26 10:24:11,001 ERROR Axure.DataBase.Module_Purchase.PurchaseOrderDAO - Error al mostrar el listado de orden de venta por Id. Referencia a objeto no establecida como instancia de un objeto.   en Axure.DataBase.Module_Purchase.PurchaseOrderDAO.GetById(Int32 Id) en C:\Users\VCiceia\Documents\DesarrolloSoftware\Axure\back_end\Axure\DataBase\Module_Purchase\PurchaseOrderDAO.cs:línea 101
2020-06-26 10:24:21,823 ERROR Axure.DataBase.Module_Purchase.PurchaseOrderDAO - Error al mostrar el listado de orden de venta por Id. Referencia a objeto no establecida como instancia de un objeto.   en Axure.DataBase.Module_Purchase.PurchaseOrderDAO.GetById(Int32 Id) en C:\Users\VCiceia\Documents\DesarrolloSoftware\Axure\back_end\Axure\DataBase\Module_Purchase\PurchaseOrderDAO.cs:línea 101
